// Smoke test for dsh-token-viewer (regenerated by scripts/build-client.mjs):
// 1. node --check on lib/index.js + lib/client.js
// 2. Host half: apply() registers the /api/billing/balance route; the handler
//    proxies DeepSeek /user/balance (ok / no-key / provider-error paths).
// 3. Client bundle: loader registration, apply() registrations (incl. the
//    openSession inject face), and renders of TokenDock / SidebarTokenPanel /
//    BalanceRow / PerSessionList via ReactDOMServer.
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const pkg = path.resolve(__dirname, '..');
const bundle = path.join(pkg, 'lib/client.js');
const hostFile = path.join(pkg, 'lib/index.js');
const reactRoot = process.env.DSH_REACT_ROOT ?? 'C:/Users/cbn/.dsh/profiles/node_modules';

// The host half imports harness packages. When this checkout has no
// node_modules (fresh clone), junction the harness install's node_modules
// from $DSH_HARNESS_NODE_MODULES so the smoke test still runs against a real
// install.
const localNodeModules = path.join(pkg, 'node_modules');
if (!fs.existsSync(localNodeModules) && process.env.DSH_HARNESS_NODE_MODULES) {
  fs.symlinkSync(process.env.DSH_HARNESS_NODE_MODULES, localNodeModules, 'junction');
}

// --- 1. syntax ---
execFileSync(process.execPath, ['--check', bundle], { stdio: 'inherit' });
execFileSync(process.execPath, ['--check', hostFile], { stdio: 'inherit' });
console.log('OK: node --check passed (client.js + index.js)');

// --- 2. host route tests ---
async function hostTests() {
  const host = await import('file:///' + hostFile.replace(/\\/g, '/'));
  if (host.name !== 'dsh-token-viewer-host') throw new Error('bad host name: ' + host.name);
  if (!host.inject.includes('webServer')) throw new Error('host missing webServer inject');

  const registeredRoutes = [];
  let keyResolver = async () => undefined;
  let balanceConfig = { apiKeyRef: 'DEEPSEEK_API_KEY', baseURL: 'https://api.deepseek.com' };
  const projectionRegistrations = [];
  const ctx = {
    effect(fn) { fn(); },
    inject(services, cb) {
      cb({
        settings: { register: () => ({ get: () => balanceConfig }) },
        sessionProjections: { register: (def) => { projectionRegistrations.push(def); } },
        effect: () => {},
      });
    },
    webServer: {
      register(route) { registeredRoutes.push(route); return () => {}; },
    },
    credentials: {
      resolve: async () => keyResolver(),
    },
  };
  host.apply(ctx);
  const balanceRoute = registeredRoutes.find((r) => r.path === '/api/billing/balance');
  const pricingRoute = registeredRoutes.find((r) => r.path === '/api/billing/pricing');
  if (balanceRoute === undefined) throw new Error('balance route not registered');
  if (balanceRoute.kind !== 'exact') throw new Error('wrong balance route kind: ' + JSON.stringify(balanceRoute));
  if (pricingRoute === undefined) throw new Error('pricing route not registered');

  // modelUsage + usageLog projections: registered with key + fold
  const keys = projectionRegistrations.map((def) => def.key);
  if (projectionRegistrations.length !== 2 || keys[0] !== 'modelUsage' || keys[1] !== 'usageLog') {
    throw new Error('projections not registered: ' + JSON.stringify(keys));
  }
  const mu = projectionRegistrations[0];
  if (JSON.stringify(mu.init()) !== JSON.stringify({ byModel: {} })) throw new Error('modelUsage init wrong');
  const ul = projectionRegistrations[1];
  if (JSON.stringify(ul.init()) !== JSON.stringify({ entries: [] })) throw new Error('usageLog init wrong');
  const ev = (model, usage, time = 1755000000000) => ({ type: 'assistant/message', time, data: { message: { source: { model } }, usage } });
  let st = mu.init();
  st = mu.apply(st, ev('deepseek-v4-flash', { inputTokens: 1000, outputTokens: 2000, cacheReadTokens: 500, cacheWriteTokens: 100 }));
  st = mu.apply(st, ev('deepseek-v4-pro', { inputTokens: 10, outputTokens: 20 }));
  if (st.byModel['deepseek-v4-flash'].requests !== 1 || st.byModel['deepseek-v4-pro'].outputTokens !== 20) {
    throw new Error('modelUsage fold wrong: ' + JSON.stringify(st));
  }
  let log = ul.init();
  log = ul.apply(log, ev('deepseek-v4-flash', { inputTokens: 1000, outputTokens: 2000, cacheReadTokens: 500, cacheWriteTokens: 100 }, 111));
  log = ul.apply(log, ev('deepseek-v4-pro', undefined, 222));
  log = ul.apply(log, ev('', { inputTokens: 1, outputTokens: 1 }, 333));
  log = ul.apply(log, { type: 'turn/start', time: 444, data: {} });
  const logJson = JSON.stringify(log.entries);
  if (log.entries.length !== 1 || log.entries[0].t !== 111 || log.entries[0].m !== 'deepseek-v4-flash'
      || log.entries[0].i !== 1000 || log.entries[0].o !== 2000 || log.entries[0].r !== 500 || log.entries[0].w !== 100) {
    throw new Error('usageLog fold wrong: ' + logJson);
  }
  console.log('OK: host registers modelUsage + usageLog projections and folds assistant usage');

  function fakeRes() {
    let status = 0;
    let body = '';
    return {
      res: {
        writeHead(s) { status = s; },
        end(b) { body = b; },
      },
      status: () => status,
      body: () => body,
    };
  }

  const originalFetch = global.fetch;

  try {
    // no key -> 503 no-api-key
    keyResolver = async () => undefined;
    let f = fakeRes();
    await balanceRoute.handler({}, f.res);
    let parsed = JSON.parse(f.body());
    if (f.status() !== 503 || parsed.ok !== false || parsed.error.code !== 'no-api-key') {
      throw new Error('no-key path wrong: ' + f.status() + ' ' + f.body());
    }
    console.log('OK: host route 503 no-api-key');

    // provider ok -> mapped balance
    keyResolver = async () => ({ value: 'sk-test', source: 'credentials.yaml' });
    global.fetch = async () => ({
      ok: true,
      status: 200,
      json: async () => ({ is_available: true, balance_infos: [{ currency: 'CNY', total_balance: 12.34, granted_balance: 0, topped_up_balance: 12.34 }] }),
    });
    f = fakeRes();
    await balanceRoute.handler({}, f.res);
    parsed = JSON.parse(f.body());
    if (f.status() !== 200 || parsed.ok !== true || parsed.totalBalance !== 12.34 || parsed.currency !== 'CNY' || parsed.isAvailable !== true) {
      throw new Error('ok path wrong: ' + f.status() + ' ' + f.body());
    }
    console.log('OK: host route 200 balance mapping');

    // settings namespace supplies the base URL + credential ref
    balanceConfig = { apiKeyRef: 'MY_KEY', baseURL: 'https://custom.example.com' };
    keyResolver = async () => ({ value: 'sk-custom', source: 'credentials.yaml' });
    global.fetch = async (url) => {
      if (url !== 'https://custom.example.com/user/balance') throw new Error('wrong url: ' + url);
      return { ok: true, status: 200, json: async () => ({ is_available: true, balance_infos: [{ currency: 'USD', total_balance: 5, granted_balance: 0, topped_up_balance: 5 }] }) };
    };
    f = fakeRes();
    await balanceRoute.handler({}, f.res);
    parsed = JSON.parse(f.body());
    if (f.status() !== 200 || parsed.currency !== 'USD') {
      throw new Error('settings-config path wrong: ' + f.status() + ' ' + f.body());
    }
    console.log('OK: host route honors the settings namespace');

    // provider http error -> status passthrough + provider-error
    balanceConfig = { apiKeyRef: 'DEEPSEEK_API_KEY', baseURL: 'https://api.deepseek.com' };
    keyResolver = async () => ({ value: 'sk-test', source: 'credentials.yaml' });
    global.fetch = async () => ({ ok: false, status: 401, text: async () => 'unauthorized' });
    f = fakeRes();
    await balanceRoute.handler({}, f.res);
    parsed = JSON.parse(f.body());
    if (f.status() !== 401 || parsed.ok !== false || parsed.error.code !== 'provider-error' || parsed.error.status !== 401) {
      throw new Error('provider-error path wrong: ' + f.status() + ' ' + f.body());
    }
    console.log('OK: host route 401 provider-error passthrough');

    // fetch rejection -> 502 provider-error
    global.fetch = async () => { throw new Error('boom') };
    f = fakeRes();
    await balanceRoute.handler({}, f.res);
    parsed = JSON.parse(f.body());
    if (f.status() !== 502 || parsed.ok !== false || parsed.error.code !== 'provider-error') {
      throw new Error('network-error path wrong: ' + f.status() + ' ' + f.body());
    }
    console.log('OK: host route 502 provider-error');

    // pricing route: unreachable page -> builtin fallback (fresh module, no cache)
    global.fetch = async () => { throw new Error('offline') };
    f = fakeRes();
    await pricingRoute.handler({}, f.res);
    parsed = JSON.parse(f.body());
    if (parsed.ok !== true || parsed.source !== 'builtin' || parsed.rows['deepseek-v4-pro'].offPeak.outputPerM !== 13.5) {
      throw new Error('pricing fallback path wrong: ' + f.body());
    }
    console.log('OK: pricing route falls back to the built-in table');

    // pricing route: official page parsed (fresh module instance, no cache)
    const freshHost = await import('file:///' + hostFile.replace(/\\/g, '/') + '?pricing=' + Date.now());
    const freshRoutes = [];
    const freshCtx = {
      effect(fn) { fn(); },
      inject(services, cb) {
        cb({
          settings: { register: () => ({ get: () => balanceConfig }) },
          sessionProjections: { register: () => {} },
          effect: () => {},
        });
      },
      webServer: { register(r) { freshRoutes.push(r); return () => {}; } },
      credentials: { resolve: async () => keyResolver() },
    };
    freshHost.apply(freshCtx);
    const freshPricing = freshRoutes.find((r) => r.path === '/api/billing/pricing');
    if (freshPricing === undefined) throw new Error('fresh pricing route missing');
    const pricingHtml = `
      <h2>DeepSeek-V4-Flash-0731</h2>
      <table><tr><th>类别</th><th>空闲时段</th><th>高峰时段</th></tr>
      <tr><td>输入（缓存命中）</td><td>0.05元</td><td>0.10元</td></tr>
      <tr><td>输入（缓存未命中）</td><td>1.5元</td><td>3.0元</td></tr>
      <tr><td>输出</td><td>4.5元</td><td>9.0元</td></tr></table>
      <h2>DeepSeek-V4-Pro-0813</h2>
      <table><tr><th>类别</th><th>空闲时段</th><th>高峰时段</th></tr>
      <tr><td>输入（缓存命中）</td><td>0.15元</td><td>0.30元</td></tr>
      <tr><td>输入（缓存未命中）</td><td>4.5元</td><td>9.0元</td></tr>
      <tr><td>输出</td><td>13.5元</td><td>27.0元</td></tr></table>`;
    global.fetch = async () => ({ ok: true, status: 200, text: async () => pricingHtml });
    f = fakeRes();
    await freshPricing.handler({}, f.res);
    parsed = JSON.parse(f.body());
    if (parsed.ok !== true || parsed.source !== 'official') throw new Error('pricing official path wrong: ' + f.body());
    if (parsed.rows['deepseek-v4-flash'].offPeak.inputPerM !== 1.5
        || parsed.rows['deepseek-v4-flash'].offPeak.outputPerM !== 4.5
        || parsed.rows['deepseek-v4-flash'].offPeak.cacheReadPerM !== 0.05
        || parsed.rows['deepseek-v4-pro'].peak.outputPerM !== 27) {
      throw new Error('pricing parse wrong: ' + JSON.stringify(parsed.rows));
    }
    console.log('OK: pricing route parses the official page (peak = 2x off-peak)');
  } finally {
    global.fetch = originalFetch;
  }
}

// --- 3. client bundle tests ---
function clientTests() {
  let registered = null;
  global.window = { __ModuleLoader__: { load(entry) { registered = entry; } } };
  global.document = {
    querySelector() { return null; },
    createElement() {
      return { dataset: {}, set textContent(v) { this._text = v; }, appendChild() {} };
    },
    head: { appendChild() {} },
  };

  require(bundle);

  if (!registered) throw new Error('loader.load was not called');
  if (registered.id !== 'dsh-token-viewer') throw new Error('bad id: ' + registered.id);

  const req = (spec) => {
    if (spec === 'react') return require(path.join(reactRoot, 'react'));
    if (spec === 'react/jsx-runtime') return require(path.join(reactRoot, 'react/jsx-runtime'));
    if (spec === '@deepseek-ai/dsh-client-ui-primitives') return {};
    if (spec === '@deepseek-ai/dsh-client-runtime/client') {
      // Minimal defineStore stand-in: enough for createTokenDetailStore().
      return {
        defineStore: (decl) => {
          let state = typeof decl.init === 'function' ? decl.init() : decl.init;
          const listeners = new Set();
          const actions = {};
          for (const [name, mutator] of Object.entries(decl.actions)) {
            actions[name] = (...args) => {
              const draft = JSON.parse(JSON.stringify(state));
              mutator(draft, ...args);
              state = draft;
              for (const fn of listeners) fn();
            };
          }
          return {
            getSnapshot: () => state,
            subscribe: (fn) => { listeners.add(fn); return () => listeners.delete(fn); },
            actions,
            create: () => ({ getSnapshot: () => state, subscribe: (fn) => { listeners.add(fn); return () => listeners.delete(fn); }, actions }),
          };
        },
      };
    }
    throw new Error('unexpected require: ' + spec);
  };
  const mod = registered.factory(req);
  if (typeof mod.apply !== 'function') throw new Error('no apply export');
  for (const name of ['SidebarRoot', 'SidebarTokenPanel', 'BalanceRow', 'PerSessionList', 'TokenDetailPanel', 'TokenDock', 'createTokenDetailStore']) {
    if (typeof mod[name] !== 'function' && (mod[name] === null || typeof mod[name] !== 'object')) {
      throw new Error('missing export ' + name);
    }
  }
  console.log('OK: factory exports apply/SidebarRoot/SidebarTokenPanel/BalanceRow/PerSessionList/TokenDetailPanel/TokenDock');

  // apply() registrations, including the openSession inject face
  const registeredSlots = [];
  const ctx = {
    effect(fn) { fn(); },
    locale: { register() {} },
    slots: {
      inject(name, cb) { registeredSlots.push(cb()); return () => {}; },
      register(opts, component) {
        const entry = { ...opts, Component: component, dispose: () => {} };
        registeredSlots.push(entry);
        return entry;
      },
    },
    layout: { toggleSidebar() {} },
    sessions: { open() {} },
    workspaces: { startSession() {} },
    settingsScope: { bind: () => ({ getSnapshot: () => undefined, subscribe: () => () => {} }) },
  };
  mod.apply(ctx);
  const shell = registeredSlots.find((e) => e && e.name === 'sidebar');
  if (!shell) throw new Error('sidebar shell not registered');
  const header = registeredSlots.find((e) => e && e.name === 'sidebar.workspaces.header');
  if (!header || header.Component !== mod.SidebarTokenPanel) throw new Error('header slot wrong');
  if (typeof header.inject !== 'function') throw new Error('header inject face missing');
  const face = header.inject();
  if (typeof face.openSession !== 'function') throw new Error('openSession inject face missing');
  const dock = registeredSlots.find((e) => e && e.name === 'conversation.input.dock');
  if (!dock || dock.id !== 'token-viewer' || dock.order !== 20) throw new Error('dock slot wrong');
  const overlay = registeredSlots.find((e) => e && e.name === 'shell.overlay');
  if (!overlay || overlay.id !== 'token-viewer-detail' || overlay.order !== 10 || overlay.Component !== mod.TokenDetailPanel) {
    throw new Error('overlay slot wrong: ' + JSON.stringify(overlay));
  }
  if (overlay.store !== header.store) throw new Error('card and drawer must share one store handle');
  console.log('OK: apply registers sidebar shell, header card, dock strip, and overlay drawer (shared store)');

  // renders
  const ReactDOMServer = require(path.join(reactRoot, 'react-dom/server'));
  const { createElement } = require(path.join(reactRoot, 'react'));
  const t = (key, params) => {
    const dict = {
      input: 'Input', output: 'Output', cacheHit: 'Cache hit', context: 'Context',
      title: 'Token Usage', sessions: 'sessions', tokens: 'tokens', balance: 'Balance',
      refresh: 'Refresh', balanceUnavailable: 'Balance unavailable', perSession: 'per-conversation',
      expand: 'Expand', collapse: 'Collapse', detail: 'Usage details', total: 'Total usage',
      byProject: 'By project', byConversation: 'By conversation', close: 'Close', ungrouped: 'Ungrouped',
      cost: 'Est. cost', realUsage: 'Real usage', range: 'Time range', today: 'Today', last7d: '7d',
      all: 'All', time: 'Time', trend: 'Usage trend', trendExact: 'bucketed by request commit time',
      modelStats: 'Model stats', model: 'Model', realTotal: 'Real consumption Tokens', requests: 'Requests',
      totalCost: 'Total cost', avgCost: 'Avg. cost', freshInput: 'Fresh input', cacheHitRate: 'Cache hit rate',
      requestLogs: 'Request logs', projectStats: 'By project', noData: 'No data', last14d: '14d', last30d: '30d',
    };
    const base = dict[key] ?? key;
    return params ? base + ':' + JSON.stringify(params) : base;
  };

  // TokenDock
  const dockProps = {
    useProjection: (key) => {
      if (key === 'tokenUsage') return { uncachedInputTokens: 1200, outputTokens: 3450, cacheReadTokens: 11000, cacheWriteTokens: 300 };
      if (key === 'contextPressure') return { projectedTokens: 15200, contextWindow: 64000 };
      return undefined;
    },
    t,
  };
  const dockHtml = ReactDOMServer.renderToStaticMarkup(createElement(mod.TokenDock, dockProps));
  if (!dockHtml.includes('data-token-viewer')) throw new Error('dock html missing marker');
  console.log('OK: TokenDock renders');

  // SidebarTokenPanel: aggregate + closed per-session toggle (balance loading -> no row)
  const panelProps = {
    wide: true,
    t,
    openSession: () => {},
    useSessions: (sel) => sel({
      byId: {
        a: { id: 'a', displayTitle: '会话A', projectionValues: { tokenUsage: { uncachedInputTokens: 1200, outputTokens: 3450, cacheReadTokens: 11000, cacheWriteTokens: 300 } } },
        b: { id: 'b', displayTitle: '会话B', projectionValues: { tokenUsage: { uncachedInputTokens: 800, outputTokens: 500, cacheReadTokens: 2000, cacheWriteTokens: 100 } } },
        c: { id: 'c', displayTitle: '会话C', projectionValues: {} },
      },
    }),
  };
  const panelHtml = ReactDOMServer.renderToStaticMarkup(createElement(mod.SidebarTokenPanel, panelProps));
  if (!panelHtml.includes('data-token-viewer-sidebar')) throw new Error('panel marker missing');
  if (!panelHtml.includes('15.4K')) throw new Error('panel aggregate wrong: ' + panelHtml);
  if (!panelHtml.includes('per-conversation')) throw new Error('panel missing per-session toggle: ' + panelHtml);
  if (panelHtml.includes('Balance unavailable') || panelHtml.includes('¥')) {
    throw new Error('balance row should not render during loading');
  }
  console.log('OK: SidebarTokenPanel renders aggregate + per-session toggle (balance loading)');

  // rail -> nothing
  const railHtml = ReactDOMServer.renderToStaticMarkup(createElement(mod.SidebarTokenPanel, { ...panelProps, wide: false }));
  if (railHtml !== '') throw new Error('rail should render nothing');
  console.log('OK: SidebarTokenPanel hidden in rail');

  // BalanceRow: ok / error / loading
  const balanceOk = ReactDOMServer.renderToStaticMarkup(createElement(mod.BalanceRow, {
    balance: { status: 'ok', balance: { ok: true, currency: 'CNY', totalBalance: 12.34, grantedBalance: 0, toppedUpBalance: 12.34, isAvailable: true } },
    onRefresh: () => {},
    t,
  }));
  if (!balanceOk.includes('¥12.34')) throw new Error('balance ok row wrong: ' + balanceOk);
  const balanceErr = ReactDOMServer.renderToStaticMarkup(createElement(mod.BalanceRow, {
    balance: { status: 'error', error: 'no-api-key' }, onRefresh: () => {}, t,
  }));
  if (!balanceErr.includes('Balance unavailable')) throw new Error('balance error row wrong: ' + balanceErr);
  const balanceLoading = ReactDOMServer.renderToStaticMarkup(createElement(mod.BalanceRow, {
    balance: { status: 'loading' }, onRefresh: () => {}, t,
  }));
  if (balanceLoading !== '') throw new Error('balance loading should render nothing');
  console.log('OK: BalanceRow ok/error/loading states');

  // PerSessionList: closed toggle, open rows, empty
  const rows = [
    { id: 'a', title: '会话A', input: 12500, output: 3450, total: 15950 },
    { id: 'b', title: '会话B', input: 2900, output: 500, total: 3400 },
  ];
  const closed = ReactDOMServer.renderToStaticMarkup(createElement(mod.PerSessionList, { rows, open: false, onToggle: () => {}, onOpen: () => {}, t }));
  if (!closed.includes('Expand') || closed.includes('会话A')) throw new Error('closed list wrong: ' + closed);
  const open = ReactDOMServer.renderToStaticMarkup(createElement(mod.PerSessionList, { rows, open: true, onToggle: () => {}, onOpen: () => {}, t }));
  if (!open.includes('会话A') || !open.includes('会话B')) throw new Error('open list wrong: ' + open);
  const empty = ReactDOMServer.renderToStaticMarkup(createElement(mod.PerSessionList, { rows: [], open: true, onToggle: () => {}, onOpen: () => {}, t }));
  if (empty !== '') throw new Error('empty list should render nothing');
  console.log('OK: PerSessionList closed/open/empty states');

  // TokenDetailPanel: closed -> nothing; open -> totals + projects + conversations
  const detailProps = (open) => ({
    t,
    openSession: () => {},
    getDefaultModel: () => 'deepseek-v4-flash',
    useStore: (sel) => sel({ open }),
    useSessions: (sel) => sel({
      byId: {
        a: { id: 'a', displayTitle: '会话A', updatedAt: Date.now(), projectionValues: { tokenUsage: { uncachedInputTokens: 1200, outputTokens: 3450, cacheReadTokens: 11000, cacheWriteTokens: 300 }, modelUsage: { byModel: { 'deepseek-v4-flash': { uncachedInputTokens: 1200, outputTokens: 3450, cacheReadTokens: 11000, cacheWriteTokens: 300, requests: 1 } } } } },
        b: { id: 'b', displayTitle: '会话B', updatedAt: Date.now(), projectionValues: { tokenUsage: { uncachedInputTokens: 800, outputTokens: 500, cacheReadTokens: 2000, cacheWriteTokens: 100 }, modelUsage: { byModel: { 'deepseek-v4-pro': { uncachedInputTokens: 800, outputTokens: 500, cacheReadTokens: 2000, cacheWriteTokens: 100, requests: 1 } } } } },
      },
    }),
    useWorkspaces: (sel) => sel({
      items: [
        { workspaceId: 'w1', title: '项目A', sessionIds: ['a'] },
        { workspaceId: 'w2', title: '项目B', sessionIds: ['b'] },
      ],
    }),
    actions: { setOpen: () => {} },
  });
  const detailClosed = ReactDOMServer.renderToStaticMarkup(createElement(mod.TokenDetailPanel, detailProps(false)));
  if (detailClosed !== '') throw new Error('closed detail panel should render nothing');
  const detailOpen = ReactDOMServer.renderToStaticMarkup(createElement(mod.TokenDetailPanel, detailProps(true)));
  if (!detailOpen.includes('data-token-detail')) throw new Error('detail panel marker missing');
  for (const label of ['Real consumption Tokens', 'Requests', 'Total cost', 'Cache hit rate', 'Fresh input', 'Usage trend', 'Request logs', 'By project', 'Model stats', 'deepseek-v4-flash', 'deepseek-v4-pro', 'By conversation', 'Today', '7d', '14d', '30d', 'All']) {
    if (!detailOpen.includes(label)) throw new Error('detail panel missing "' + label + '"');
  }
  if (!detailOpen.includes('会话A') || !detailOpen.includes('会话B')) throw new Error('detail panel log rows missing');
  if (!detailOpen.includes('deepseek-v4-flash') || !detailOpen.includes('deepseek-v4-pro')) {
    throw new Error('detail panel model rows missing');
  }
  console.log('OK: TokenDetailPanel closed/open with CC Switch hero, trend, tabs, log rows, and ranges');
}

(async () => {
  try {
    await hostTests();
    clientTests();
    console.log('ALL SMOKE TESTS PASSED');
  } catch (error) {
    console.error('FAILED: ' + error.message);
    process.exit(1);
  }
})();
